<?php

return array(
    'Programmation php',
    'Programmation mysql',
    'Programmation web',
    'Programmation javascript',
    'Programmation symfony',
    'Programmation zend',
    'Programmation nodejs',
    'Programmation prestashop',
    'Programmation wordpress',
    'Programmation dupral',

    'Programmeur php',
    'Programmeur mysql',
    'Programmeur web',
    'Programmeur javascript',
    'Programmeur symfony',
    'Programmeur zend',
    'Programmeur nodejs',
    'Programmeur prestashop',
    'Programmeur wordpress',
    'Programmeur dupral',

    'Développeur php',
    'Développeur mysql',
    'Développeur web',
    'Développeur javascript',
    'Développeur symfony',
    'Développeur zend',
    'Développeur nodejs',
    'Développeur prestashop',
    'Développeur wordpress',
    'Développeur dupral',

    'Entrepreneur php',
    'Entrepreneur mysql',
    'Entrepreneur web',
    'Entrepreneur javascript',
    'Entrepreneur symfony',
    'Entrepreneur zend',
    'Entrepreneur nodejs',
    'Entrepreneur prestashop',
    'Entrepreneur wordpress',
    'Entrepreneur dupral',
    'Entrepreneur chambéry',

    'Ingénieur php',
    'Ingénieur mysql',
    'Ingénieur web',
    'Ingénieur javascript',
    'Ingénieur symfony',
    'Ingénieur zend',
    'Ingénieur nodejs',
    'Ingénieur prestashop',
    'Ingénieur wordpress',
    'Ingénieur dupral',

    'Concepteur php',
    'Concepteur mysql',
    'Concepteur web',
    'Concepteur javascript',
    'Concepteur symfony',
    'Concepteur zend',
    'Concepteur nodejs',
    'Concepteur prestashop',
    'Concepteur wordpress',
    'Concepteur dupral',

    'Veille php',
    'Veille mysql',
    'Veille web',
    'Veille javascript',
    'Veille symfony',
    'Veille zend',
    'Veille nodejs',
    'Veille prestashop',
    'Veille wordpress',
    'Veille dupral',

    'Informaticien php',
    'Informaticien mysql',
    'Informaticien web',
    'Informaticien javascript',
    'Informaticien symfony',
    'Informaticien zend',
    'Informaticien nodejs',
    'Informaticien prestashop',
    'Informaticien wordpress',
    'Informaticien dupral',
    'Informaticien chambéry',

    'Expert php',
    'Expert mysql',
    'Expert web',
    'Expert javascript',
    'Expert symfony',
    'Expert zend',
    'Expert nodejs',
    'Expert prestashop',
    'Expert wordpress',
    'Expert dupral',

    'Technicien php',
    'Technicien mysql',
    'Technicien web',
    'Technicien javascript',
    'Technicien symfony',
    'Technicien zend',
    'Technicien nodejs',
    'Technicien prestashop',
    'Technicien wordpress',
    'Technicien dupral',

    'Intégrateur php',
    'Intégrateur mysql',
    'Intégrateur web',
    'Intégrateur javascript',
    'Intégrateur symfony',
    'Intégrateur zend',
    'Intégrateur nodejs',
    'Intégrateur prestashop',
    'Intégrateur wordpress',
    'Intégrateur dupral',

    'Chef de projet php',
    'Chef de projet mysql',
    'Chef de projet web',
    'Chef de projet javascript',
    'Chef de projet symfony',
    'Chef de projet zend',
    'Chef de projet nodejs',
    'Chef de projet prestashop',
    'Chef de projet wordpress',
    'Chef de projet dupral',

    'Chambéry',
);
