#!/usr/bin/env php
<?php

use Core\TwitterApi;
use Model\Block;
use Model\Follower;
use Model\Friend;
use Model\Hide;
use Model\User;

set_time_limit(0);
ini_set('memory_limit', '512M');

include __DIR__ . '/../bootstrap.php';

$api = new TwitterApi(
    TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET,
    TWITTER_OAUTH_TOKEN,
    TWITTER_OAUTH_TOKEN_SECRET
);

$followers = $api->get('followers/ids', array(
    'screen_name' => TWITTER_SCREEN_NAME
));

foreach($followers->ids as $id) {

    Follower::$data['_' . $id] = (new Follower($id))->getData();
}

Follower::save();

$friends = $api->get('friends/ids', array(
    'screen_name' => TWITTER_SCREEN_NAME
));

foreach($friends->ids as $id) {

    Friend::$data['_' . $id] = (new Friend($id))->getData();
}

Friend::save();

$blocks = $api->get('blocks/ids', array(
    'screen_name' => TWITTER_SCREEN_NAME
));

foreach($blocks->ids as $id) {

    Block::$data['_' . $id] = (new Block($id))->getData();
}

Block::save();

User::load();
Hide::load();

foreach(TwitterApi::$searches as $search) {

    $lastMd5File = null;

    echo "\nTerm: " . $search . "\n--------------------\n";

    for($page = 1; $page <= 50; $page++) {

        $fileCache = DIR_CACHE . '/' . md5($search . ';' . $page) . '.json';

        $items = $api->getCached('users/search', array(
            'q' => $search,
            'count' => 20,
            'page' => $page,
        ), $fileCache);

        if($lastMd5File === (string) md5_file($fileCache)) {

            break;
        }

        $lastMd5File = (string) md5_file($fileCache);

        echo "Page: " . $page . " - " . ($page*20) . "\n";

        foreach($items as $item) {

            $idStr = '_' . $item['id'];

            $item['following'] = array_key_exists($idStr, Friend::$data);
            $item['following_date'] = null;
            $item['following_back'] = array_key_exists($idStr, Follower::$data);
            $item['following_back_date'] = null;
            $item['last_status'] = isset($item['status']['created_at']) ? $item['status']['created_at'] : null;

            if(true === $item['following']
                && (!array_key_exists($idStr, User::$data)
                    || is_null(User::$data[$idStr]['following_date']))) {

                $item['following_date'] = date('Y-m-d H:i:s');
            }

            if(true === $item['following_back']
                && (!array_key_exists($idStr, User::$data)
                    || is_null(User::$data[$idStr]['following_back_date']))) {

                $item['following_back_date'] = date('Y-m-d H:i:s');
            }

            User::$data[$idStr] = (new User($item['id']))->hydrate($item)->getData();
        }
    }
}

// Delete blocked users
foreach(User::$data as $id=>$data) {

    $idStr = '_' . $data['id'];

    if((string) $data['screen_name'] === (string) TWITTER_SCREEN_NAME
        || array_key_exists($idStr, Block::$data)
        || array_key_exists($idStr, Hide::$data)) {

        unset(User::$data[$idStr]);
    }
}

echo count(User::$data) . "\n";

User::save($blocks);
