#!/usr/bin/env php
<?php

use Core\TwitterApi;
use Model\Block;
use Model\Hide;
use Model\User;

set_time_limit(0);
ini_set('memory_limit', '512M');

include __DIR__ . '/../bootstrap.php';

$api = new TwitterApi(
    TWITTER_CONSUMER_KEY,
    TWITTER_CONSUMER_SECRET,
    TWITTER_OAUTH_TOKEN,
    TWITTER_OAUTH_TOKEN_SECRET
);

$api->sync('followers/list', array(
    'screen_name' => TWITTER_SCREEN_NAME,
    'count' => 200,
), '\\Model\\Follower', null, null);

$api->sync('friends/list', array(
    'screen_name' => TWITTER_SCREEN_NAME,
    'count' => 200,
), '\\Model\\Friend', null, null);

$api->sync('blocks/list', array(
    'screen_name' => TWITTER_SCREEN_NAME,
    'count' => 200,
), '\\Model\\Block', null, null);

foreach(TwitterApi::$searches as $search) {

    $api->sync('users/search', array(
        'q' => $search,
        'count' => 20,
    ), '\\Model\\User');
}

User::load();
Block::load();
Hide::load();

// Delete blocked users
foreach(User::$data as $id=>$data) {

    $idStr = '_' . $data['id'];

    if((string) $data['screen_name'] === (string) TWITTER_SCREEN_NAME
        || array_key_exists($idStr, Block::$data)
        || array_key_exists($idStr, Hide::$data)) {

        unset(User::$data[$idStr]);
    }
}

echo count(User::$data) . "\n";

User::save();
